/** Seed data for the formula library (also used as a fallback when the CMS database is unavailable). */
export interface FormulaVar {
  symbol: string;
  meaning: string;
}
export interface FormulaData {
  slug: string;
  name: string;
  category: string;
  latex: string;
  summary: string;
  variables: FormulaVar[];
  explanation: string;
  example: string;
  relatedCalculator?: string;
  relatedTopics: string[];
  faqs: { q: string; a: string }[];
}

export const FORMULA_CATEGORIES = ["Algebra", "Geometry", "Trigonometry", "Calculus", "Statistics", "Linear Algebra"] as const;

export const FORMULAS: FormulaData[] = [
  {
    slug: "quadratic-formula",
    name: "Quadratic Formula",
    category: "Algebra",
    latex: "x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}",
    summary: "Solves any quadratic equation ax² + bx + c = 0.",
    variables: [{ symbol: "a, b, c", meaning: "Coefficients of ax² + bx + c = 0 (a ≠ 0)" }, { symbol: "x", meaning: "The solutions (roots)" }],
    explanation: "The quadratic formula comes from completing the square on $ax^2 + bx + c = 0$. The expression under the square root, $b^2 - 4ac$, is the **discriminant**: positive gives two real roots, zero gives one repeated root, and negative gives two complex roots.",
    example: "Solve $x^2 - 3x - 10 = 0$: $a = 1, b = -3, c = -10$. Then $\\Delta = 9 + 40 = 49$, so $x = \\frac{3 \\pm 7}{2}$, giving $x = 5$ or $x = -2$.",
    relatedCalculator: "quadratic-formula-calculator",
    relatedTopics: ["vertex-formula", "difference-of-squares"],
    faqs: [{ q: "Can the quadratic formula solve every quadratic?", a: "Yes — every quadratic equation, including ones with complex roots." }],
  },
  {
    slug: "vertex-formula",
    name: "Vertex of a Parabola",
    category: "Algebra",
    latex: "h = -\\frac{b}{2a},\\quad k = f(h)",
    summary: "Finds the turning point (vertex) of y = ax² + bx + c.",
    variables: [{ symbol: "(h, k)", meaning: "Coordinates of the vertex" }, { symbol: "a, b, c", meaning: "Coefficients of the quadratic" }],
    explanation: "The parabola is symmetric about the vertical line $x = -\\frac{b}{2a}$. Substituting this x-value into the function gives the minimum (if $a > 0$) or maximum (if $a < 0$) value.",
    example: "For $y = x^2 - 4x + 3$: $h = \\frac{4}{2} = 2$, $k = 4 - 8 + 3 = -1$. Vertex $(2, -1)$.",
    relatedCalculator: "graphing-calculator",
    relatedTopics: ["quadratic-formula"],
    faqs: [{ q: "What is vertex form?", a: "y = a(x − h)² + k, which shows the vertex (h, k) directly." }],
  },
  {
    slug: "difference-of-squares",
    name: "Difference of Squares",
    category: "Algebra",
    latex: "a^2 - b^2 = (a - b)(a + b)",
    summary: "Factors the difference of two perfect squares.",
    variables: [{ symbol: "a, b", meaning: "Any expressions" }],
    explanation: "Multiplying $(a-b)(a+b)$ gives $a^2 + ab - ab - b^2 = a^2 - b^2$; the middle terms cancel. Recognizing this pattern makes factoring and simplifying rational expressions fast.",
    example: "$4x^2 - 25 = (2x)^2 - 5^2 = (2x - 5)(2x + 5)$.",
    relatedCalculator: "factoring-calculator",
    relatedTopics: ["sum-of-cubes"],
    faqs: [{ q: "Can a sum of squares be factored?", a: "Not over the real numbers: a² + b² only factors using complex numbers, (a + bi)(a − bi)." }],
  },
  {
    slug: "sum-of-cubes",
    name: "Sum and Difference of Cubes",
    category: "Algebra",
    latex: "a^3 \\pm b^3 = (a \\pm b)(a^2 \\mp ab + b^2)",
    summary: "Factors sums and differences of perfect cubes.",
    variables: [{ symbol: "a, b", meaning: "Any expressions" }],
    explanation: "Remember **SOAP** for the signs: Same, Opposite, Always Positive. The quadratic factor $a^2 \\mp ab + b^2$ never factors further over the reals.",
    example: "$x^3 - 8 = (x - 2)(x^2 + 2x + 4)$.",
    relatedCalculator: "factoring-calculator",
    relatedTopics: ["difference-of-squares"],
    faqs: [],
  },
  {
    slug: "exponent-rules",
    name: "Exponent Rules",
    category: "Algebra",
    latex: "a^m a^n = a^{m+n},\; \\frac{a^m}{a^n} = a^{m-n},\; (a^m)^n = a^{mn},\; a^{-n} = \\frac{1}{a^n}",
    summary: "The laws for multiplying, dividing and raising powers.",
    variables: [{ symbol: "a", meaning: "Base (a ≠ 0 for negative or zero exponents)" }, { symbol: "m, n", meaning: "Exponents" }],
    explanation: "Each rule follows from the definition of a power as repeated multiplication. Also: $a^0 = 1$ and $a^{1/n} = \\sqrt[n]{a}$.",
    example: "$\\frac{2^5 \\cdot 2^3}{2^4} = 2^{5+3-4} = 2^4 = 16$.",
    relatedCalculator: "exponent-calculator",
    relatedTopics: ["logarithm-rules"],
    faqs: [{ q: "Why is a⁰ = 1?", a: "Because aⁿ / aⁿ = a⁰ must equal 1 for any nonzero a." }],
  },
  {
    slug: "logarithm-rules",
    name: "Logarithm Rules",
    category: "Algebra",
    latex: "\\log_b(xy) = \\log_b x + \\log_b y,\; \\log_b\\frac{x}{y} = \\log_b x - \\log_b y,\; \\log_b x^k = k\\log_b x",
    summary: "Product, quotient, power and change-of-base rules for logarithms.",
    variables: [{ symbol: "b", meaning: "Base (b > 0, b ≠ 1)" }, { symbol: "x, y", meaning: "Positive arguments" }],
    explanation: "Logarithms turn multiplication into addition. The **change of base** formula $\\log_b x = \\frac{\\ln x}{\\ln b}$ lets you evaluate any logarithm.",
    example: "$\\log_2 32 - \\log_2 4 = \\log_2 8 = 3$.",
    relatedCalculator: "log-calculator",
    relatedTopics: ["exponent-rules"],
    faqs: [{ q: "What is ln?", a: "The natural logarithm, log base e ≈ 2.71828." }],
  },
  {
    slug: "slope-formula",
    name: "Slope Formula",
    category: "Algebra",
    latex: "m = \\frac{y_2 - y_1}{x_2 - x_1}",
    summary: "The slope (rate of change) of the line through two points.",
    variables: [{ symbol: "(x₁, y₁), (x₂, y₂)", meaning: "Two points on the line" }, { symbol: "m", meaning: "Slope" }],
    explanation: "Slope is **rise over run**: the change in y divided by the change in x. Parallel lines have equal slopes; perpendicular lines have slopes whose product is −1.",
    example: "Through $(1, 2)$ and $(4, 8)$: $m = \\frac{8-2}{4-1} = 2$.",
    relatedCalculator: "slope-calculator",
    relatedTopics: ["distance-formula", "midpoint-formula"],
    faqs: [{ q: "What is point-slope form?", a: "y − y₁ = m(x − x₁)." }],
  },
  {
    slug: "distance-formula",
    name: "Distance Formula",
    category: "Geometry",
    latex: "d = \\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}",
    summary: "Distance between two points in the plane.",
    variables: [{ symbol: "d", meaning: "Distance" }, { symbol: "(x₁, y₁), (x₂, y₂)", meaning: "The two points" }],
    explanation: "This is the Pythagorean theorem applied to the right triangle formed by the horizontal and vertical differences.",
    example: "From $(1, 2)$ to $(4, 6)$: $d = \\sqrt{9 + 16} = 5$.",
    relatedCalculator: "slope-calculator",
    relatedTopics: ["pythagorean-theorem", "midpoint-formula"],
    faqs: [],
  },
  {
    slug: "midpoint-formula",
    name: "Midpoint Formula",
    category: "Geometry",
    latex: "M = \\left(\\frac{x_1 + x_2}{2}, \\frac{y_1 + y_2}{2}\\right)",
    summary: "The point halfway between two points.",
    variables: [{ symbol: "M", meaning: "Midpoint" }],
    explanation: "Average the x-coordinates and average the y-coordinates.",
    example: "Midpoint of $(2, 3)$ and $(8, 7)$ is $(5, 5)$.",
    relatedCalculator: "slope-calculator",
    relatedTopics: ["distance-formula"],
    faqs: [],
  },
  {
    slug: "pythagorean-theorem",
    name: "Pythagorean Theorem",
    category: "Geometry",
    latex: "a^2 + b^2 = c^2",
    summary: "Relates the sides of a right triangle.",
    variables: [{ symbol: "a, b", meaning: "Legs" }, { symbol: "c", meaning: "Hypotenuse (side opposite the right angle)" }],
    explanation: "In any right triangle, the area of the square on the hypotenuse equals the sum of the areas of the squares on the legs. The converse also holds: if $a^2 + b^2 = c^2$, the triangle is right.",
    example: "Legs 5 and 12: $c = \\sqrt{25 + 144} = 13$.",
    relatedCalculator: "pythagorean-theorem-calculator",
    relatedTopics: ["distance-formula", "law-of-cosines"],
    faqs: [{ q: "What are Pythagorean triples?", a: "Whole-number solutions such as (3, 4, 5), (5, 12, 13) and (8, 15, 17)." }],
  },
  {
    slug: "area-of-a-circle",
    name: "Area of a Circle",
    category: "Geometry",
    latex: "A = \\pi r^2",
    summary: "Area enclosed by a circle of radius r.",
    variables: [{ symbol: "A", meaning: "Area" }, { symbol: "r", meaning: "Radius" }],
    explanation: "Slice the circle into thin sectors and rearrange them into an almost-rectangle of width $\\pi r$ and height $r$. Circumference is $C = 2\\pi r$.",
    example: "$r = 5$: $A = 25\\pi \\approx 78.54$.",
    relatedCalculator: "area-calculator",
    relatedTopics: ["volume-of-a-cylinder", "volume-of-a-sphere"],
    faqs: [{ q: "What if I know the diameter?", a: "Use r = d/2, or A = πd²/4." }],
  },
  {
    slug: "area-of-a-triangle",
    name: "Area of a Triangle",
    category: "Geometry",
    latex: "A = \\frac{1}{2}bh",
    summary: "Half of base times height.",
    variables: [{ symbol: "b", meaning: "Base" }, { symbol: "h", meaning: "Perpendicular height to that base" }],
    explanation: "A triangle is half of a parallelogram with the same base and height. Without the height, use Heron's formula or $A = \\frac12 ab\\sin C$.",
    example: "$b = 6, h = 4$: $A = 12$.",
    relatedCalculator: "area-calculator",
    relatedTopics: ["herons-formula"],
    faqs: [],
  },
  {
    slug: "herons-formula",
    name: "Heron's Formula",
    category: "Geometry",
    latex: "A = \\sqrt{s(s-a)(s-b)(s-c)},\\quad s = \\frac{a+b+c}{2}",
    summary: "Triangle area from its three side lengths.",
    variables: [{ symbol: "a, b, c", meaning: "Side lengths" }, { symbol: "s", meaning: "Semi-perimeter" }],
    explanation: "Useful when no height is known. If the value under the root is negative, the sides cannot form a triangle.",
    example: "Sides 3, 4, 5: $s = 6$, $A = \\sqrt{6\\cdot3\\cdot2\\cdot1} = 6$.",
    relatedCalculator: "triangle-calculator",
    relatedTopics: ["area-of-a-triangle"],
    faqs: [],
  },
  {
    slug: "volume-of-a-sphere",
    name: "Volume of a Sphere",
    category: "Geometry",
    latex: "V = \\frac{4}{3}\\pi r^3",
    summary: "Volume of a ball of radius r; surface area is 4πr².",
    variables: [{ symbol: "r", meaning: "Radius" }],
    explanation: "Archimedes showed a sphere fills two thirds of its circumscribed cylinder. The formula can be derived by integrating the areas of circular cross-sections.",
    example: "$r = 3$: $V = 36\\pi \\approx 113.1$.",
    relatedCalculator: "volume-calculator",
    relatedTopics: ["volume-of-a-cylinder"],
    faqs: [],
  },
  {
    slug: "volume-of-a-cylinder",
    name: "Volume of a Cylinder",
    category: "Geometry",
    latex: "V = \\pi r^2 h",
    summary: "Base area times height.",
    variables: [{ symbol: "r", meaning: "Radius of the base" }, { symbol: "h", meaning: "Height" }],
    explanation: "Any prism or cylinder has volume equal to base area × height. A cone with the same base and height has one third of this volume.",
    example: "$r = 3, h = 5$: $V = 45\\pi \\approx 141.4$.",
    relatedCalculator: "volume-calculator",
    relatedTopics: ["area-of-a-circle"],
    faqs: [],
  },
  {
    slug: "law-of-sines",
    name: "Law of Sines",
    category: "Trigonometry",
    latex: "\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C}",
    summary: "Relates sides to the sines of their opposite angles in any triangle.",
    variables: [{ symbol: "a, b, c", meaning: "Sides" }, { symbol: "A, B, C", meaning: "Opposite angles" }],
    explanation: "Use it when you know two angles and a side (ASA/AAS) or two sides and a non-included angle (SSA — watch for the ambiguous case).",
    example: "$A = 30°, C = 90°, c = 10$: $a = 10\\sin 30° = 5$.",
    relatedCalculator: "triangle-calculator",
    relatedTopics: ["law-of-cosines"],
    faqs: [],
  },
  {
    slug: "law-of-cosines",
    name: "Law of Cosines",
    category: "Trigonometry",
    latex: "c^2 = a^2 + b^2 - 2ab\\cos C",
    summary: "Generalizes the Pythagorean theorem to all triangles.",
    variables: [{ symbol: "C", meaning: "Angle between sides a and b" }],
    explanation: "When $C = 90°$, $\\cos C = 0$ and it reduces to $a^2 + b^2 = c^2$. Use it for SSS and SAS triangles.",
    example: "$a = 5, b = 7, C = 60°$: $c^2 = 25 + 49 - 35 = 39$, $c \\approx 6.24$.",
    relatedCalculator: "triangle-calculator",
    relatedTopics: ["law-of-sines", "pythagorean-theorem"],
    faqs: [],
  },
  {
    slug: "pythagorean-identity",
    name: "Pythagorean Identity",
    category: "Trigonometry",
    latex: "\\sin^2\\theta + \\cos^2\\theta = 1",
    summary: "The fundamental trigonometric identity.",
    variables: [{ symbol: "θ", meaning: "Any angle" }],
    explanation: "On the unit circle a point is $(\\cos\\theta, \\sin\\theta)$, and its distance from the origin is 1. Dividing by $\\cos^2\\theta$ gives $1 + \\tan^2\\theta = \\sec^2\\theta$.",
    example: "If $\\sin\\theta = \\frac35$ in quadrant I, then $\\cos\\theta = \\frac45$.",
    relatedCalculator: "simplify-calculator",
    relatedTopics: ["law-of-sines"],
    faqs: [],
  },
  {
    slug: "power-rule",
    name: "Power Rule (Derivatives)",
    category: "Calculus",
    latex: "\\frac{d}{dx}x^n = n x^{n-1}",
    summary: "Derivative of a power of x.",
    variables: [{ symbol: "n", meaning: "Any real exponent" }],
    explanation: "Bring the exponent down as a coefficient and reduce the exponent by one. It works for negative and fractional exponents too, e.g. $\\frac{d}{dx}\\sqrt{x} = \\frac{1}{2\\sqrt x}$.",
    example: "$\\frac{d}{dx}(4x^3) = 12x^2$.",
    relatedCalculator: "derivative-calculator",
    relatedTopics: ["product-rule", "chain-rule"],
    faqs: [],
  },
  {
    slug: "product-rule",
    name: "Product Rule",
    category: "Calculus",
    latex: "(fg)' = f'g + fg'",
    summary: "Derivative of a product of two functions.",
    variables: [{ symbol: "f, g", meaning: "Differentiable functions" }],
    explanation: "Differentiate one factor at a time while keeping the other fixed, then add.",
    example: "$\\frac{d}{dx}(x^2\\sin x) = 2x\\sin x + x^2\\cos x$.",
    relatedCalculator: "derivative-calculator",
    relatedTopics: ["quotient-rule", "chain-rule"],
    faqs: [],
  },
  {
    slug: "quotient-rule",
    name: "Quotient Rule",
    category: "Calculus",
    latex: "\\left(\\frac{f}{g}\\right)' = \\frac{f'g - fg'}{g^2}",
    summary: "Derivative of a quotient.",
    variables: [{ symbol: "f, g", meaning: "Numerator and denominator (g ≠ 0)" }],
    explanation: "Mnemonic: “low d-high minus high d-low, over low squared”.",
    example: "$\\frac{d}{dx}\\frac{x}{x+1} = \\frac{(x+1) - x}{(x+1)^2} = \\frac{1}{(x+1)^2}$.",
    relatedCalculator: "derivative-calculator",
    relatedTopics: ["product-rule"],
    faqs: [],
  },
  {
    slug: "chain-rule",
    name: "Chain Rule",
    category: "Calculus",
    latex: "\\frac{d}{dx}f(g(x)) = f'(g(x))\\,g'(x)",
    summary: "Derivative of a composite function.",
    variables: [{ symbol: "f", meaning: "Outer function" }, { symbol: "g", meaning: "Inner function" }],
    explanation: "Differentiate the outside (leaving the inside alone), then multiply by the derivative of the inside.",
    example: "$\\frac{d}{dx}\\sin(x^2) = \\cos(x^2)\\cdot 2x$.",
    relatedCalculator: "derivative-calculator",
    relatedTopics: ["power-rule"],
    faqs: [],
  },
  {
    slug: "lhopitals-rule",
    name: "L'Hôpital's Rule",
    category: "Calculus",
    latex: "\\lim_{x\\to a}\\frac{f(x)}{g(x)} = \\lim_{x\\to a}\\frac{f'(x)}{g'(x)}",
    summary: "Evaluates 0/0 and ∞/∞ indeterminate limits.",
    variables: [{ symbol: "f, g", meaning: "Functions with f(a) = g(a) = 0 (or both infinite)" }],
    explanation: "Only apply it to indeterminate forms $\\frac00$ or $\\frac{\\infty}{\\infty}$, and differentiate numerator and denominator **separately** (not with the quotient rule).",
    example: "$\\lim_{x\\to0}\\frac{\\sin x}{x} = \\lim_{x\\to0}\\frac{\\cos x}{1} = 1$.",
    relatedCalculator: "limit-calculator",
    relatedTopics: ["power-rule"],
    faqs: [],
  },
  {
    slug: "fundamental-theorem-of-calculus",
    name: "Fundamental Theorem of Calculus",
    category: "Calculus",
    latex: "\\int_a^b f(x)\\,dx = F(b) - F(a),\\quad F' = f",
    summary: "Connects definite integrals to antiderivatives.",
    variables: [{ symbol: "F", meaning: "Any antiderivative of f" }, { symbol: "a, b", meaning: "Limits of integration" }],
    explanation: "To evaluate a definite integral of a continuous function, find any antiderivative and subtract its values at the endpoints. The constant $C$ cancels.",
    example: "$\\int_0^3 x^2\\,dx = \\frac{27}{3} - 0 = 9$.",
    relatedCalculator: "integral-calculator",
    relatedTopics: ["integration-by-parts"],
    faqs: [],
  },
  {
    slug: "integration-by-parts",
    name: "Integration by Parts",
    category: "Calculus",
    latex: "\\int u\\,dv = uv - \\int v\\,du",
    summary: "Integrates products of functions; the reverse of the product rule.",
    variables: [{ symbol: "u", meaning: "Part to differentiate" }, { symbol: "dv", meaning: "Part to integrate" }],
    explanation: "Choose $u$ using **LIATE** (Logarithmic, Inverse trig, Algebraic, Trigonometric, Exponential) — the earlier in the list, the better a choice for $u$.",
    example: "$\\int xe^x\\,dx$: $u = x$, $dv = e^x dx$ gives $xe^x - e^x + C$.",
    relatedCalculator: "integral-calculator",
    relatedTopics: ["fundamental-theorem-of-calculus"],
    faqs: [],
  },
  {
    slug: "mean-formula",
    name: "Mean (Average)",
    category: "Statistics",
    latex: "\\bar{x} = \\frac{1}{n}\\sum_{i=1}^{n} x_i",
    summary: "The arithmetic average of a data set.",
    variables: [{ symbol: "xᵢ", meaning: "Data values" }, { symbol: "n", meaning: "Number of values" }],
    explanation: "Add all values and divide by the count. The mean is sensitive to outliers; the median is more robust.",
    example: "Mean of 2, 4, 9 is $\\frac{15}{3} = 5$.",
    relatedCalculator: "statistics-calculator",
    relatedTopics: ["standard-deviation-formula"],
    faqs: [],
  },
  {
    slug: "standard-deviation-formula",
    name: "Standard Deviation",
    category: "Statistics",
    latex: "s = \\sqrt{\\frac{\\sum (x_i - \\bar{x})^2}{n - 1}}",
    summary: "Measures spread of data around the mean.",
    variables: [{ symbol: "s", meaning: "Sample standard deviation" }, { symbol: "x̄", meaning: "Mean" }],
    explanation: "For an entire population divide by $n$ instead of $n-1$ (giving $\\sigma$). About 68% of normally distributed data lie within one standard deviation of the mean.",
    example: "Data 2, 4, 4, 4, 5, 5, 7, 9 has $\\sigma = 2$.",
    relatedCalculator: "standard-deviation-calculator",
    relatedTopics: ["mean-formula"],
    faqs: [],
  },
  {
    slug: "combinations-formula",
    name: "Combinations and Permutations",
    category: "Statistics",
    latex: "\\binom{n}{r} = \\frac{n!}{r!(n-r)!},\\quad P(n,r) = \\frac{n!}{(n-r)!}",
    summary: "Counting selections (order irrelevant) and arrangements (order matters).",
    variables: [{ symbol: "n", meaning: "Total items" }, { symbol: "r", meaning: "Items chosen" }],
    explanation: "Each combination of $r$ items can be arranged in $r!$ ways, so $P(n,r) = r!\\binom{n}{r}$.",
    example: "$\\binom{10}{3} = 120$, $P(10,3) = 720$.",
    relatedCalculator: "combination-calculator",
    relatedTopics: ["binomial-probability"],
    faqs: [],
  },
  {
    slug: "binomial-probability",
    name: "Binomial Probability",
    category: "Statistics",
    latex: "P(X = k) = \\binom{n}{k}p^k(1-p)^{n-k}",
    summary: "Probability of exactly k successes in n independent trials.",
    variables: [{ symbol: "n", meaning: "Trials" }, { symbol: "p", meaning: "Success probability" }, { symbol: "k", meaning: "Successes" }],
    explanation: "Mean $np$, variance $np(1-p)$. Requires a fixed number of independent trials with the same success probability.",
    example: "3 heads in 10 fair coin flips: $\\binom{10}{3}(0.5)^{10} \\approx 0.117$.",
    relatedCalculator: "combination-calculator",
    relatedTopics: ["combinations-formula", "probability-rules"],
    faqs: [],
  },
  {
    slug: "probability-rules",
    name: "Probability Rules",
    category: "Statistics",
    latex: "P(A \\cup B) = P(A) + P(B) - P(A \\cap B),\\quad P(A') = 1 - P(A)",
    summary: "Addition, complement and multiplication rules.",
    variables: [{ symbol: "A, B", meaning: "Events" }],
    explanation: "For independent events $P(A \\cap B) = P(A)P(B)$. Subtracting the intersection avoids double counting outcomes in both events.",
    example: "$P(A) = 0.5, P(B) = 0.3$ independent: $P(A\\cup B) = 0.65$.",
    relatedCalculator: "probability-calculator",
    relatedTopics: ["binomial-probability"],
    faqs: [],
  },
  {
    slug: "determinant-2x2",
    name: "Determinant of a Matrix",
    category: "Linear Algebra",
    latex: "\\det\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix} = ad - bc",
    summary: "Scalar that tells whether a matrix is invertible.",
    variables: [{ symbol: "a, b, c, d", meaning: "Matrix entries" }],
    explanation: "Geometrically, $|\\det A|$ is the area (or volume) scale factor of the transformation. Larger matrices use cofactor expansion or row reduction.",
    example: "$\\det\\begin{bmatrix}1&2\\\\3&4\\end{bmatrix} = 4 - 6 = -2$.",
    relatedCalculator: "matrix-calculator",
    relatedTopics: ["matrix-inverse-2x2", "cramers-rule"],
    faqs: [],
  },
  {
    slug: "matrix-inverse-2x2",
    name: "Inverse of a 2×2 Matrix",
    category: "Linear Algebra",
    latex: "\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}^{-1} = \\frac{1}{ad - bc}\\begin{bmatrix} d & -b \\\\ -c & a \\end{bmatrix}",
    summary: "Swap the diagonal, negate the off-diagonal, divide by the determinant.",
    variables: [{ symbol: "ad − bc", meaning: "Determinant (must be nonzero)" }],
    explanation: "The inverse satisfies $AA^{-1} = I$. For larger matrices, row-reduce $[A \\mid I]$ to $[I \\mid A^{-1}]$.",
    example: "$\\begin{bmatrix}2&1\\\\1&3\\end{bmatrix}^{-1} = \\frac15\\begin{bmatrix}3&-1\\\\-1&2\\end{bmatrix}$.",
    relatedCalculator: "matrix-calculator",
    relatedTopics: ["determinant-2x2"],
    faqs: [],
  },
  {
    slug: "cramers-rule",
    name: "Cramer's Rule",
    category: "Linear Algebra",
    latex: "x_i = \\frac{\\det(A_i)}{\\det(A)}",
    summary: "Solves square linear systems with determinants.",
    variables: [{ symbol: "Aᵢ", meaning: "A with column i replaced by the constants" }],
    explanation: "Works only when $\\det A \\neq 0$. Practical for 2×2 and 3×3 systems; elimination is faster for larger ones.",
    example: "$2x + 3y = 12, x - y = 1$: $D = -5$, $x = \\frac{-15}{-5} = 3$, $y = 2$.",
    relatedCalculator: "system-of-equations-calculator",
    relatedTopics: ["determinant-2x2"],
    faqs: [],
  },
];

export const formulaMap = new Map(FORMULAS.map((f) => [f.slug, f]));
