import type { CalculatorDef } from "./types";
import { INSTANT } from "./instant";

const req = (v: string | undefined, name: string) => {
  if (!v || !v.trim()) throw new Error(`Please enter ${name}.`);
  return v.trim();
};

export const CALCULATORS: CalculatorDef[] = [
  {
    slug: "algebra-calculator",
    title: "Algebra Calculator",
    shortTitle: "Algebra",
    category: "algebra",
    icon: "Sigma",
    description: "Free algebra calculator that solves equations, simplifies expressions and factors polynomials with verified step-by-step solutions.",
    kind: "engine",
    fields: [{ name: "q", label: "Expression or equation", type: "expression", placeholder: "e.g. 3(x - 2) + 4 = 2x + 7", default: "3(x - 2) + 4 = 2x + 7" }],
    build: (v) => req(v.q, "an expression"),
    intro: "Type any algebra problem — an equation, an expression to simplify, or a polynomial to factor — and get an exact answer with every step explained. Each result is independently verified by substitution or numerical checks before it is shown.",
    howTo: ["Enter your problem using the keyboard or the math keypad (use ^ for powers).", "Add a command like “simplify”, “factor” or “expand” if you want a specific form.", "Press Solve to see the answer, each step, the formulas used and the verification."],
    examples: [
      { problem: "3(x - 2) + 4 = 2x + 7", answer: "x = 9", note: "Distribute, collect like terms, isolate x." },
      { problem: "simplify (x^2 - 9)/(x - 3)", answer: "x + 3, x ≠ 3" },
      { problem: "factor 2x^2 + 7x + 3", answer: "(2x + 1)(x + 3)" },
    ],
    faqs: [
      { q: "What kinds of algebra problems can it solve?", a: "Linear, quadratic, polynomial, rational, radical, exponential and logarithmic equations; systems of equations; inequalities; and simplifying, expanding or factoring expressions." },
      { q: "How do I enter exponents and fractions?", a: "Use ^ for powers (x^2) and / for fractions ((x+1)/(x-2)). You can also paste LaTeX such as \\frac{1}{2} or use the math keyboard." },
      { q: "Are the answers checked?", a: "Yes. Equation solutions are substituted back into the original equation and simplifications are compared numerically with the original expression." },
    ],
    related: ["equation-solver", "factoring-calculator", "simplify-calculator", "quadratic-formula-calculator"],
    formulas: ["quadratic-formula", "difference-of-squares"],
    keywords: ["algebra calculator", "algebra solver", "solve algebra"],
  },
  {
    slug: "equation-solver",
    title: "Equation Solver",
    shortTitle: "Equations",
    category: "algebra",
    icon: "Equal",
    description: "Solve linear, quadratic, polynomial, rational, radical, exponential, logarithmic and trigonometric equations step by step.",
    kind: "engine",
    fields: [
      { name: "q", label: "Equation", type: "expression", placeholder: "e.g. 2^(x+1) = 32", default: "x^3 - 6x^2 + 11x - 6 = 0" },
      { name: "var", label: "Solve for", type: "text", placeholder: "x", optional: true, help: "Leave blank to detect automatically." },
    ],
    build: (v) => `${req(v.q, "an equation")}${v.var?.trim() ? `, solve for ${v.var.trim()}` : ""}`,
    intro: "Our equation solver finds every real (and complex) solution, checks each one in the original equation and rejects extraneous roots — the step most students forget with radical and rational equations.",
    howTo: ["Type the equation with an equals sign.", "Optionally choose which variable to solve for (useful for formulas like A = πr²).", "Review the steps; any rejected candidate solutions are explained."],
    examples: [
      { problem: "x^3 - 6x^2 + 11x - 6 = 0", answer: "x = 1, 2, 3", note: "Rational Root Theorem + synthetic division." },
      { problem: "sqrt(x + 3) = x - 3", answer: "x = 6", note: "x = 1 is extraneous." },
      { problem: "sin(x) = 1/2", answer: "x = π/6 + 2πk, 5π/6 + 2πk" },
    ],
    faqs: [
      { q: "Does it find complex solutions?", a: "For polynomial equations, yes — complex roots are shown when there are no (or not enough) real roots." },
      { q: "What is an extraneous solution?", a: "A value produced by a valid-looking algebraic step (like squaring both sides) that does not satisfy the original equation. The solver tests and removes them." },
      { q: "Can it solve for a variable in a formula?", a: "Yes. Enter the formula and choose the variable, e.g. “v = u + at, solve for t”." },
    ],
    related: ["algebra-calculator", "system-of-equations-calculator", "quadratic-formula-calculator", "inequality-calculator"],
    formulas: ["quadratic-formula", "logarithm-rules"],
    keywords: ["equation solver", "solve for x", "equation calculator"],
  },
  {
    slug: "quadratic-formula-calculator",
    title: "Quadratic Formula Calculator",
    shortTitle: "Quadratic",
    category: "algebra",
    icon: "Parabola",
    description: "Solve ax² + bx + c = 0 with the quadratic formula. Shows the discriminant, exact roots, decimal values and factoring.",
    kind: "engine",
    fields: [
      { name: "a", label: "a", type: "number", default: "1" },
      { name: "b", label: "b", type: "number", default: "-3" },
      { name: "c", label: "c", type: "number", default: "-10" },
    ],
    build: (v) => {
      const a = Number(req(v.a, "a")), b = Number(req(v.b, "b")), c = Number(req(v.c, "c"));
      if (a === 0) throw new Error("a cannot be 0 for a quadratic equation.");
      return `${a}x^2 + (${b})x + (${c}) = 0`;
    },
    intro: "Enter the coefficients of ax² + bx + c = 0. The calculator computes the discriminant, explains what it tells you about the roots, applies the quadratic formula exactly (simplifying square roots), and shows factoring or completing the square as an alternative method.",
    howTo: ["Rewrite your equation in standard form ax² + bx + c = 0.", "Enter a, b and c (a cannot be zero).", "Read the discriminant, the exact roots and their decimal approximations."],
    examples: [
      { problem: "x² − 3x − 10 = 0", answer: "x = −2, x = 5" },
      { problem: "2x² − 3x − 1 = 0", answer: "x = (3 ± √17)/4" },
      { problem: "x² + 2x + 5 = 0", answer: "x = −1 ± 2i" },
    ],
    faqs: [
      { q: "What does the discriminant tell me?", a: "Δ = b² − 4ac. If Δ > 0 there are two real roots, if Δ = 0 one repeated root, and if Δ < 0 two complex conjugate roots." },
      { q: "When should I factor instead?", a: "If Δ is a perfect square, the roots are rational and the quadratic factors nicely over the integers — factoring is usually faster." },
      { q: "Does it handle decimals?", a: "Yes. Decimal coefficients are converted to exact fractions when possible." },
    ],
    related: ["equation-solver", "factoring-calculator", "graphing-calculator"],
    formulas: ["quadratic-formula", "vertex-formula"],
    keywords: ["quadratic formula calculator", "quadratic equation solver", "discriminant calculator"],
  },
  {
    slug: "system-of-equations-calculator",
    title: "System of Equations Calculator",
    shortTitle: "Systems",
    category: "algebra",
    icon: "Rows3",
    description: "Solve systems of 2 or 3 linear (or nonlinear) equations with Gaussian elimination, substitution and Cramer's rule.",
    kind: "engine",
    fields: [
      { name: "e1", label: "Equation 1", type: "expression", default: "2x + 3y = 12" },
      { name: "e2", label: "Equation 2", type: "expression", default: "x - y = 1" },
      { name: "e3", label: "Equation 3 (optional)", type: "expression", optional: true },
    ],
    build: (v) => [v.e1, v.e2, v.e3].filter((e) => e && e.trim()).join("; ") || req("", "equations"),
    intro: "Solve simultaneous equations with full row-reduction steps. Linear systems are solved with Gauss–Jordan elimination and checked with Cramer's rule; nonlinear systems use substitution.",
    howTo: ["Enter one equation per box.", "Use the same variable names in each equation (x, y, z).", "See the augmented matrix, each row operation and the final solution checked in every equation."],
    examples: [
      { problem: "2x + 3y = 12, x − y = 1", answer: "x = 3, y = 2" },
      { problem: "x + y + z = 6, 2x − y + z = 3, x + 2y − z = 2", answer: "x = 1, y = 2, z = 3" },
    ],
    faqs: [
      { q: "What if the system has no solution?", a: "Row reduction produces a contradictory row (0 = c). The calculator reports that the system is inconsistent." },
      { q: "What about infinitely many solutions?", a: "The solution is expressed in terms of free variables (parameters)." },
    ],
    related: ["matrix-calculator", "equation-solver", "graphing-calculator"],
    formulas: ["cramers-rule"],
    keywords: ["system of equations calculator", "simultaneous equations solver", "elimination calculator"],
  },
  {
    slug: "inequality-calculator",
    title: "Inequality Calculator",
    shortTitle: "Inequalities",
    category: "algebra",
    icon: "ChevronsLeftRight",
    description: "Solve linear, compound, polynomial and rational inequalities with sign charts and interval notation.",
    kind: "engine",
    fields: [{ name: "q", label: "Inequality", type: "expression", placeholder: "e.g. (x - 1)/(x + 2) <= 0", default: "x^2 - x - 6 > 0" }],
    build: (v) => req(v.q, "an inequality"),
    intro: "Get the solution set in interval notation with a full sign chart. The solver remembers to flip the inequality when dividing by a negative and never includes points where a denominator is zero.",
    howTo: ["Use <, >, <= or >= (or ≤, ≥).", "Compound inequalities like 1 < 2x + 3 < 7 are supported.", "Read the sign chart to see why each interval is included or excluded."],
    examples: [
      { problem: "x² − x − 6 > 0", answer: "(−∞, −2) ∪ (3, ∞)" },
      { problem: "−2x + 4 ≥ 10", answer: "x ≤ −3" },
    ],
    faqs: [
      { q: "Why does the inequality sign flip?", a: "Multiplying or dividing both sides by a negative number reverses the order of the numbers, so the inequality sign must reverse too." },
      { q: "What is interval notation?", a: "A compact way to write solution sets: parentheses exclude an endpoint, brackets include it, and ∪ joins separate pieces." },
    ],
    related: ["equation-solver", "algebra-calculator"],
    keywords: ["inequality calculator", "solve inequalities", "interval notation calculator"],
  },
  {
    slug: "factoring-calculator",
    title: "Factoring Calculator",
    shortTitle: "Factoring",
    category: "algebra",
    icon: "Brackets",
    description: "Factor polynomials completely: GCF, trinomials, difference of squares, sum of cubes and higher-degree polynomials.",
    kind: "engine",
    fields: [{ name: "q", label: "Polynomial", type: "expression", default: "x^3 - 2x^2 - 9x + 18" }],
    build: (v) => `factor ${req(v.q, "a polynomial")}`,
    intro: "Factor any polynomial with a clear strategy: pull out the greatest common factor, recognize special patterns, and use the Rational Root Theorem for higher degrees. The factored form is verified by expanding it back.",
    howTo: ["Enter the polynomial.", "Press Factor to see the strategy and the complete factorization."],
    examples: [
      { problem: "x³ − 2x² − 9x + 18", answer: "(x − 2)(x − 3)(x + 3)" },
      { problem: "4x² − 25", answer: "(2x − 5)(2x + 5)" },
    ],
    faqs: [{ q: "Why can't some quadratics be factored?", a: "If the discriminant is not a perfect square, the roots are irrational or complex and the quadratic does not factor over the integers." }],
    related: ["algebra-calculator", "quadratic-formula-calculator", "simplify-calculator"],
    formulas: ["difference-of-squares", "sum-of-cubes"],
    keywords: ["factoring calculator", "factor polynomials", "polynomial factoring"],
  },
  {
    slug: "simplify-calculator",
    title: "Simplify Calculator",
    shortTitle: "Simplify",
    category: "algebra",
    icon: "Wand2",
    description: "Simplify algebraic, rational, exponential, logarithmic and trigonometric expressions step by step.",
    kind: "engine",
    fields: [{ name: "q", label: "Expression", type: "expression", default: "(x^2 - 4)/(x^2 + 4x + 4)" }],
    build: (v) => `simplify ${req(v.q, "an expression")}`,
    intro: "Combine like terms, cancel common factors and apply identities to get the simplest equivalent form — including the domain restrictions that cancelling hides.",
    howTo: ["Enter the expression.", "Read the simplified form and any restrictions on the variable."],
    examples: [{ problem: "(x² − 4)/(x² + 4x + 4)", answer: "(x − 2)/(x + 2), x ≠ −2" }, { problem: "sin²x + cos²x", answer: "1" }],
    faqs: [{ q: "Why are restrictions listed?", a: "Cancelling a factor removes a value that made the original denominator zero. That value is still excluded from the domain." }],
    related: ["algebra-calculator", "factoring-calculator"],
    keywords: ["simplify calculator", "simplify expressions", "rational expression calculator"],
  },
  {
    slug: "derivative-calculator",
    title: "Derivative Calculator",
    shortTitle: "Derivatives",
    category: "calculus",
    icon: "TrendingUp",
    description: "Differentiate functions step by step using the power, product, quotient and chain rules. Supports higher-order and partial derivatives.",
    kind: "engine",
    fields: [
      { name: "f", label: "f(x) =", type: "expression", default: "x^2 sin(x)" },
      { name: "var", label: "Variable", type: "text", default: "x" },
      { name: "order", label: "Order", type: "select", default: "1", options: [{ value: "1", label: "First derivative" }, { value: "2", label: "Second derivative" }, { value: "3", label: "Third derivative" }] },
      { name: "at", label: "Evaluate at (optional)", type: "number", optional: true },
    ],
    build: (v) => {
      const ord = { "1": "", "2": "second ", "3": "third " }[v.order ?? "1"] ?? "";
      const at = v.at?.trim() ? ` at ${v.var || "x"} = ${v.at.trim()}` : "";
      return `${ord}derivative of ${req(v.f, "a function")} with respect to ${v.var?.trim() || "x"}${at}`;
    },
    intro: "Our derivative calculator names every rule it uses — sum, power, product, quotient and chain rule — and shows the intermediate derivatives. The result is verified against numerical differentiation at several points.",
    howTo: ["Enter the function, e.g. x^2 sin(x) or e^(3x)/x.", "Choose the variable and the order.", "Optionally evaluate the derivative at a point to get a slope."],
    examples: [
      { problem: "d/dx [x² sin x]", answer: "2x sin x + x² cos x", note: "Product rule" },
      { problem: "d/dx [sin(x²)]", answer: "2x cos(x²)", note: "Chain rule" },
      { problem: "d²/dx² [e^(2x)]", answer: "4e^(2x)" },
    ],
    faqs: [
      { q: "Which rules does it explain?", a: "Constant, power, constant multiple, sum, product, quotient and chain rules, plus derivatives of exponential, logarithmic, trigonometric and inverse trig functions." },
      { q: "Can it do partial derivatives?", a: "Yes — choose the variable; other letters are treated as constants." },
      { q: "How is the answer verified?", a: "The symbolic derivative is compared against a high-order finite-difference approximation at multiple sample points." },
    ],
    related: ["integral-calculator", "limit-calculator", "graphing-calculator"],
    formulas: ["power-rule", "product-rule", "quotient-rule", "chain-rule"],
    keywords: ["derivative calculator", "differentiate", "derivative step by step"],
  },
  {
    slug: "integral-calculator",
    title: "Integral Calculator",
    shortTitle: "Integrals",
    category: "calculus",
    icon: "Activity",
    description: "Compute indefinite and definite integrals step by step: power rule, substitution, integration by parts and partial fractions.",
    kind: "engine",
    fields: [
      { name: "f", label: "Integrand f(x)", type: "expression", default: "x^2 sin(x)" },
      { name: "var", label: "Variable", type: "text", default: "x" },
      { name: "lower", label: "Lower bound (optional)", type: "text", optional: true, placeholder: "e.g. 0 or -inf" },
      { name: "upper", label: "Upper bound (optional)", type: "text", optional: true, placeholder: "e.g. pi or inf" },
    ],
    build: (v) => {
      const f = req(v.f, "an integrand");
      const x = v.var?.trim() || "x";
      const lo = v.lower?.trim(), hi = v.upper?.trim();
      if ((lo && !hi) || (!lo && hi)) throw new Error("Enter both bounds for a definite integral, or neither.");
      return `integrate ${f} d${x}${lo && hi ? ` from ${lo} to ${hi}` : ""}`;
    },
    intro: "Find antiderivatives and evaluate definite or improper integrals. The calculator identifies the technique (power rule, u-substitution, integration by parts, partial fractions) and verifies the answer by differentiating it back or comparing with numerical integration.",
    howTo: ["Enter the integrand.", "Leave the bounds empty for an indefinite integral (+C), or enter both for a definite integral (use inf for ∞).", "Review the technique, the antiderivative and the verification."],
    examples: [
      { problem: "∫ x² sin x dx", answer: "−x² cos x + 2x sin x + 2cos x + C", note: "Integration by parts (twice)" },
      { problem: "∫₀³ 2x dx", answer: "9" },
      { problem: "∫ 1/(x² − 1) dx", answer: "½ ln|x − 1| − ½ ln|x + 1| + C", note: "Partial fractions" },
    ],
    faqs: [
      { q: "Why add + C?", a: "Every function has infinitely many antiderivatives that differ by a constant; +C represents all of them." },
      { q: "What if there is no elementary antiderivative?", a: "Some functions (like e^(−x²)) have none. For definite integrals the calculator still returns an accurate numerical value." },
    ],
    related: ["derivative-calculator", "limit-calculator", "area-calculator"],
    formulas: ["integration-by-parts", "fundamental-theorem-of-calculus"],
    keywords: ["integral calculator", "antiderivative calculator", "definite integral calculator"],
  },
  {
    slug: "limit-calculator",
    title: "Limit Calculator",
    shortTitle: "Limits",
    category: "calculus",
    icon: "ArrowRightToLine",
    description: "Evaluate limits step by step, including one-sided limits, limits at infinity and indeterminate forms with L'Hôpital's rule.",
    kind: "engine",
    fields: [
      { name: "f", label: "f(x)", type: "expression", default: "(x^2 - 1)/(x - 1)" },
      { name: "var", label: "Variable", type: "text", default: "x" },
      { name: "at", label: "Approaches", type: "text", default: "1", placeholder: "number, inf or -inf" },
      { name: "side", label: "Direction", type: "select", default: "both", options: [{ value: "both", label: "Two-sided" }, { value: "+", label: "From the right (+)" }, { value: "-", label: "From the left (−)" }] },
    ],
    build: (v) => `limit of ${req(v.f, "a function")} as ${v.var?.trim() || "x"} -> ${req(v.at, "the limit point")}${v.side === "+" ? "+" : v.side === "-" ? "-" : ""}`,
    intro: "Start with direct substitution, then — if you hit 0/0 or ∞/∞ — factor and cancel or apply L'Hôpital's rule. One-sided limits are compared numerically to decide whether the two-sided limit exists.",
    howTo: ["Enter the function and the point the variable approaches.", "Pick two-sided or one-sided.", "Follow the steps from substitution to the final value."],
    examples: [
      { problem: "lim(x→1) (x² − 1)/(x − 1)", answer: "2" },
      { problem: "lim(x→0) sin x / x", answer: "1" },
      { problem: "lim(x→∞) (1 + 1/x)^x", answer: "e" },
    ],
    faqs: [{ q: "When does a limit not exist?", a: "When the left- and right-hand limits differ, when the function oscillates, or when it grows without bound in different directions." }],
    related: ["derivative-calculator", "integral-calculator"],
    formulas: ["lhopitals-rule"],
    keywords: ["limit calculator", "lhopital calculator", "evaluate limits"],
  },
  {
    slug: "fraction-calculator",
    title: "Fraction Calculator",
    shortTitle: "Fractions",
    category: "arithmetic",
    icon: "Divide",
    description: "Add, subtract, multiply and divide fractions and mixed numbers with steps and simplified answers.",
    kind: "engine",
    fields: [
      { name: "a", label: "First fraction", type: "text", default: "3/4" },
      { name: "op", label: "Operation", type: "select", default: "+", options: [{ value: "+", label: "+ Add" }, { value: "-", label: "− Subtract" }, { value: "*", label: "× Multiply" }, { value: "/", label: "÷ Divide" }] },
      { name: "b", label: "Second fraction", type: "text", default: "5/6" },
    ],
    build: (v) => {
      const toExpr = (s: string) => {
        const m = /^\s*(-?\d+)\s+(\d+)\s*\/\s*(\d+)\s*$/.exec(s);
        return m ? `(${m[1]} ${m[1].startsWith("-") ? "-" : "+"} ${m[2]}/${m[3]})` : `(${s.trim()})`;
      };
      return `${toExpr(req(v.a, "the first fraction"))} ${v.op ?? "+"} ${toExpr(req(v.b, "the second fraction"))}`;
    },
    intro: "Work with fractions and mixed numbers (like 2 1/3). The answer is reduced to lowest terms and shown as a decimal.",
    howTo: ["Enter fractions as a/b and mixed numbers as “2 1/3”.", "Choose the operation.", "See the common denominator or reciprocal step and the simplified result."],
    examples: [{ problem: "3/4 + 5/6", answer: "19/12" }, { problem: "2 1/3 × 3/7", answer: "1" }],
    faqs: [{ q: "How do you add fractions with different denominators?", a: "Rewrite both with the least common denominator, add the numerators, and simplify." }],
    related: ["percentage-calculator", "lcm-calculator", "gcf-calculator"],
    keywords: ["fraction calculator", "adding fractions", "mixed numbers calculator"],
  },
  {
    slug: "percentage-calculator",
    title: "Percentage Calculator",
    shortTitle: "Percentages",
    category: "arithmetic",
    icon: "Percent",
    description: "Calculate percentages, percentage of a number, and percent increase or decrease instantly with steps.",
    kind: "instant",
    fields: [
      { name: "mode", label: "Calculation", type: "select", default: "of", options: [{ value: "of", label: "What is X% of Y?" }, { value: "what", label: "X is what % of Y?" }, { value: "change", label: "% change from X to Y" }] },
      { name: "a", label: "X", type: "number", default: "15" },
      { name: "b", label: "Y", type: "number", default: "80" },
    ],
    compute: INSTANT.percentage,
    intro: "Three percentage tools in one: find a percent of a number, find what percent one number is of another, and compute percent increase or decrease.",
    howTo: ["Choose the type of calculation.", "Enter X and Y.", "Results update instantly with the steps."],
    examples: [{ problem: "15% of 80", answer: "12" }, { problem: "18 is what % of 72?", answer: "25%" }, { problem: "% change from 50 to 65", answer: "30% increase" }],
    faqs: [{ q: "How do I calculate percent change?", a: "Subtract the old value from the new value, divide by the old value, and multiply by 100." }],
    related: ["fraction-calculator", "scientific-calculator"],
    keywords: ["percentage calculator", "percent increase calculator", "percent of a number"],
  },
  {
    slug: "gcf-calculator",
    title: "GCF Calculator",
    shortTitle: "GCF",
    category: "arithmetic",
    icon: "Hash",
    description: "Find the greatest common factor (GCD) of two or more numbers using prime factorization and the Euclidean algorithm.",
    kind: "instant",
    fields: [{ name: "numbers", label: "Numbers (comma separated)", type: "list", default: "84, 126, 210" }],
    compute: INSTANT.gcf,
    intro: "The greatest common factor is the largest number that divides all of your numbers. See it two ways: by prime factorization and by the Euclidean algorithm.",
    howTo: ["Enter two or more whole numbers separated by commas.", "Read the prime factorizations and the GCF."],
    examples: [{ problem: "GCF(84, 126, 210)", answer: "42" }],
    faqs: [{ q: "Is GCF the same as GCD and HCF?", a: "Yes — greatest common factor, greatest common divisor and highest common factor all mean the same thing." }],
    related: ["lcm-calculator", "fraction-calculator"],
    keywords: ["gcf calculator", "gcd calculator", "greatest common factor"],
  },
  {
    slug: "lcm-calculator",
    title: "LCM Calculator",
    shortTitle: "LCM",
    category: "arithmetic",
    icon: "Hash",
    description: "Find the least common multiple of two or more numbers with prime factorization steps.",
    kind: "instant",
    fields: [{ name: "numbers", label: "Numbers (comma separated)", type: "list", default: "12, 18, 30" }],
    compute: INSTANT.lcm,
    intro: "The least common multiple is the smallest number that all of your numbers divide into — essential for adding fractions with different denominators.",
    howTo: ["Enter two or more whole numbers.", "See each prime factorization and how the LCM is built."],
    examples: [{ problem: "LCM(12, 18, 30)", answer: "180" }],
    faqs: [{ q: "How are LCM and GCF related?", a: "For two numbers, LCM(a, b) × GCF(a, b) = a × b." }],
    related: ["gcf-calculator", "fraction-calculator"],
    keywords: ["lcm calculator", "least common multiple"],
  },
  {
    slug: "exponent-calculator",
    title: "Exponent Calculator",
    shortTitle: "Exponents",
    category: "arithmetic",
    icon: "Superscript",
    description: "Raise any number to any power, including negative and fractional exponents, with explanations.",
    kind: "instant",
    fields: [{ name: "base", label: "Base", type: "number", default: "2" }, { name: "exp", label: "Exponent", type: "number", default: "10" }],
    compute: INSTANT.exponent,
    intro: "Compute powers and roots: whole-number, negative and fractional exponents are all supported, with the exponent rule that applies.",
    howTo: ["Enter the base and the exponent.", "See the value and the rule used."],
    examples: [{ problem: "2^10", answer: "1024" }, { problem: "8^(1/3)", answer: "2" }],
    faqs: [{ q: "What does a negative exponent mean?", a: "a^(−n) = 1/aⁿ — the reciprocal of the positive power." }],
    related: ["log-calculator", "scientific-calculator"],
    formulas: ["exponent-rules"],
    keywords: ["exponent calculator", "power calculator"],
  },
  {
    slug: "log-calculator",
    title: "Logarithm Calculator",
    shortTitle: "Logarithms",
    category: "algebra",
    icon: "FunctionSquare",
    description: "Evaluate logarithms in any base and solve logarithmic equations step by step.",
    kind: "engine",
    fields: [{ name: "base", label: "Base", type: "text", default: "2" }, { name: "x", label: "Argument", type: "text", default: "64" }],
    build: (v) => {
      const b = req(v.base, "a base").toLowerCase();
      const x = req(v.x, "an argument");
      return b === "e" ? `ln(${x})` : b === "10" ? `log(${x})` : `log_${b}(${x})`;
    },
    intro: "Evaluate log_b(x) for any base, including the natural log (base e) and common log (base 10). Exact values are recognized when the argument is a power of the base.",
    howTo: ["Enter the base (use e for natural log).", "Enter the argument (must be positive)."],
    examples: [{ problem: "log₂ 64", answer: "6" }, { problem: "ln e³", answer: "3" }],
    faqs: [{ q: "What is the change of base formula?", a: "log_b(x) = ln(x) / ln(b). It lets you compute any logarithm with a calculator that only has ln or log." }],
    related: ["exponent-calculator", "equation-solver"],
    formulas: ["logarithm-rules"],
    keywords: ["log calculator", "logarithm calculator", "natural log calculator"],
  },
  {
    slug: "slope-calculator",
    title: "Slope Calculator",
    shortTitle: "Slope",
    category: "geometry",
    icon: "Slash",
    description: "Find the slope, equation of the line, distance and midpoint between two points.",
    kind: "instant",
    fields: [
      { name: "x1", label: "x₁", type: "number", default: "1" },
      { name: "y1", label: "y₁", type: "number", default: "2" },
      { name: "x2", label: "x₂", type: "number", default: "4" },
      { name: "y2", label: "y₂", type: "number", default: "8" },
    ],
    compute: INSTANT.slope,
    intro: "Enter two points to get the slope, slope-intercept equation, angle of inclination, distance and midpoint — all at once.",
    howTo: ["Enter the coordinates of two points.", "Results update instantly."],
    examples: [{ problem: "(1, 2) and (4, 8)", answer: "m = 2, y = 2x" }],
    faqs: [{ q: "What does a slope of 0 mean?", a: "The line is horizontal. A vertical line has an undefined slope." }],
    related: ["graphing-calculator", "triangle-calculator"],
    formulas: ["slope-formula", "distance-formula", "midpoint-formula"],
    keywords: ["slope calculator", "slope of a line", "two point slope"],
  },
  {
    slug: "area-calculator",
    title: "Area Calculator",
    shortTitle: "Area",
    category: "geometry",
    icon: "Square",
    description: "Calculate the area (and perimeter) of rectangles, squares, circles, triangles, trapezoids, parallelograms and ellipses.",
    kind: "instant",
    fields: [
      { name: "shape", label: "Shape", type: "select", default: "circle", options: ["rectangle", "square", "circle", "triangle", "trapezoid", "parallelogram", "ellipse"].map((s) => ({ value: s, label: s[0].toUpperCase() + s.slice(1) })) },
      { name: "a", label: "Length / radius / base", type: "number", default: "5" },
      { name: "b", label: "Width / height / second base", type: "number", optional: true, showIf: { field: "shape", values: ["rectangle", "triangle", "trapezoid", "parallelogram", "ellipse"] } },
      { name: "c", label: "Height", type: "number", optional: true, showIf: { field: "shape", values: ["trapezoid"] } },
    ],
    compute: INSTANT.area,
    intro: "Pick a shape and enter its measurements. The calculator shows the formula, the substitution and the result (exact in terms of π where relevant).",
    howTo: ["Choose a shape.", "Enter the measurements in the same unit.", "The area is in square units."],
    examples: [{ problem: "Circle, r = 5", answer: "25π ≈ 78.54" }, { problem: "Trapezoid, bases 6 and 10, h = 4", answer: "32" }],
    faqs: [{ q: "What units is the area in?", a: "Square units of whatever length unit you used — e.g. cm² if you entered centimeters." }],
    related: ["volume-calculator", "triangle-calculator", "geometry-solver"],
    formulas: ["area-of-a-circle", "area-of-a-triangle"],
    keywords: ["area calculator", "area of a circle calculator", "area of shapes"],
  },
  {
    slug: "volume-calculator",
    title: "Volume Calculator",
    shortTitle: "Volume",
    category: "geometry",
    icon: "Box",
    description: "Find the volume and surface area of cubes, boxes, spheres, cylinders, cones and pyramids.",
    kind: "instant",
    fields: [
      { name: "shape", label: "Solid", type: "select", default: "cylinder", options: ["cube", "box", "sphere", "cylinder", "cone", "pyramid"].map((s) => ({ value: s, label: s[0].toUpperCase() + s.slice(1) })) },
      { name: "a", label: "Side / length / radius / base area", type: "number", default: "3" },
      { name: "b", label: "Width / height", type: "number", default: "5", optional: true, showIf: { field: "shape", values: ["box", "cylinder", "cone", "pyramid"] } },
      { name: "c", label: "Height", type: "number", optional: true, showIf: { field: "shape", values: ["box"] } },
    ],
    compute: INSTANT.volume,
    intro: "Compute volume and surface area for common 3D solids with formulas and substitutions shown.",
    howTo: ["Choose a solid.", "Enter its dimensions.", "Volume is in cubic units."],
    examples: [{ problem: "Cylinder r = 3, h = 5", answer: "45π ≈ 141.37" }, { problem: "Sphere r = 2", answer: "32π/3 ≈ 33.51" }],
    faqs: [{ q: "Why is a cone one third of a cylinder?", a: "A cone with the same base and height as a cylinder holds exactly one third of its volume — a result provable with calculus." }],
    related: ["area-calculator", "geometry-solver"],
    formulas: ["volume-of-a-sphere", "volume-of-a-cylinder"],
    keywords: ["volume calculator", "volume of a cylinder", "surface area calculator"],
  },
  {
    slug: "triangle-calculator",
    title: "Triangle Calculator",
    shortTitle: "Triangles",
    category: "trigonometry",
    icon: "Triangle",
    description: "Solve any triangle from SSS, SAS or ASA: all sides, angles, area, perimeter and type using the laws of sines and cosines.",
    kind: "instant",
    fields: [
      { name: "mode", label: "Known values", type: "select", default: "sss", options: [{ value: "sss", label: "Three sides (SSS)" }, { value: "sas", label: "Two sides + included angle (SAS)" }, { value: "asa", label: "Two angles + side (ASA)" }] },
      { name: "a", label: "Side a", type: "number", default: "3", showIf: { field: "mode", values: ["sss"] } },
      { name: "b", label: "Side b", type: "number", default: "4", showIf: { field: "mode", values: ["sss", "sas"] } },
      { name: "c", label: "Side c", type: "number", default: "5" },
      { name: "angle", label: "Angle A (degrees)", type: "number", showIf: { field: "mode", values: ["sas", "asa"] } },
      { name: "angle2", label: "Angle B (degrees)", type: "number", showIf: { field: "mode", values: ["asa"] } },
    ],
    compute: INSTANT.triangle,
    intro: "Solve a triangle completely from three known values. The calculator uses the law of cosines, the law of sines and Heron's formula, and classifies the triangle.",
    howTo: ["Choose which values you know.", "Enter them (angles in degrees).", "Get all sides, angles, area and perimeter."],
    examples: [{ problem: "SSS 3, 4, 5", answer: "Right triangle, area 6" }],
    faqs: [{ q: "When does SSA (two sides and a non-included angle) fail?", a: "SSA can give zero, one or two triangles (the ambiguous case), which is why this calculator uses SSS, SAS and ASA." }],
    related: ["pythagorean-theorem-calculator", "area-calculator"],
    formulas: ["law-of-sines", "law-of-cosines", "herons-formula"],
    keywords: ["triangle calculator", "law of cosines calculator", "solve triangle"],
  },
  {
    slug: "pythagorean-theorem-calculator",
    title: "Pythagorean Theorem Calculator",
    shortTitle: "Pythagorean",
    category: "geometry",
    icon: "Triangle",
    description: "Find the hypotenuse or a missing leg of a right triangle using a² + b² = c².",
    kind: "engine",
    fields: [{ name: "a", label: "Leg a", type: "number", default: "5" }, { name: "b", label: "Leg b", type: "number", default: "12" }],
    build: (v) => `hypotenuse ${req(v.a, "leg a")} and ${req(v.b, "leg b")}`,
    intro: "In a right triangle, the square of the hypotenuse equals the sum of the squares of the legs. Enter the two legs to find the hypotenuse with verification.",
    howTo: ["Enter both legs.", "The hypotenuse is computed and checked with a² + b² = c²."],
    examples: [{ problem: "a = 5, b = 12", answer: "c = 13" }],
    faqs: [{ q: "Does it work for non-right triangles?", a: "No — use the law of cosines (see the Triangle Calculator) for other triangles." }],
    related: ["triangle-calculator", "slope-calculator"],
    formulas: ["pythagorean-theorem"],
    keywords: ["pythagorean theorem calculator", "hypotenuse calculator"],
  },
  {
    slug: "statistics-calculator",
    title: "Statistics Calculator",
    shortTitle: "Statistics",
    category: "statistics",
    icon: "BarChart3",
    description: "Descriptive statistics: mean, median, mode, range, variance, standard deviation and quartiles with steps.",
    kind: "engine",
    fields: [{ name: "data", label: "Data (comma or space separated)", type: "list", default: "4, 8, 15, 16, 23, 42" }],
    build: (v) => `statistics of ${req(v.data, "data")}`,
    intro: "Paste your data set to get every common summary statistic, with both sample and population variance and standard deviation explained.",
    howTo: ["Paste or type numbers separated by commas or spaces.", "Read center (mean, median, mode) and spread (range, variance, SD, IQR)."],
    examples: [{ problem: "4, 8, 15, 16, 23, 42", answer: "mean 18, median 15.5" }],
    faqs: [{ q: "Sample or population standard deviation?", a: "Use the sample SD (divide by n − 1) when your data is a sample from a larger group; use the population SD (divide by n) when you have every member." }],
    related: ["standard-deviation-calculator", "probability-calculator"],
    formulas: ["mean-formula", "standard-deviation-formula"],
    keywords: ["statistics calculator", "mean median mode calculator", "descriptive statistics"],
  },
  {
    slug: "standard-deviation-calculator",
    title: "Standard Deviation Calculator",
    shortTitle: "Std. deviation",
    category: "statistics",
    icon: "BarChart3",
    description: "Compute sample and population standard deviation and variance step by step.",
    kind: "engine",
    fields: [{ name: "data", label: "Data", type: "list", default: "2, 4, 4, 4, 5, 5, 7, 9" }],
    build: (v) => `standard deviation of ${req(v.data, "data")}`,
    intro: "Standard deviation measures how spread out data is around the mean. See the squared deviations, the variance and the square root for both sample and population.",
    howTo: ["Enter the data values.", "Choose the sample or population result depending on your data."],
    examples: [{ problem: "2, 4, 4, 4, 5, 5, 7, 9", answer: "σ = 2, s ≈ 2.138" }],
    faqs: [{ q: "Why divide by n − 1 for a sample?", a: "Bessel's correction: dividing by n − 1 makes the sample variance an unbiased estimate of the population variance." }],
    related: ["statistics-calculator"],
    formulas: ["standard-deviation-formula"],
    keywords: ["standard deviation calculator", "variance calculator"],
  },
  {
    slug: "probability-calculator",
    title: "Probability Calculator",
    shortTitle: "Probability",
    category: "statistics",
    icon: "Dices",
    description: "Probability of two independent events: intersection, union, complement, exactly one and neither.",
    kind: "instant",
    fields: [{ name: "pa", label: "P(A)", type: "number", default: "0.5" }, { name: "pb", label: "P(B)", type: "number", default: "0.3" }],
    compute: INSTANT.probability,
    intro: "Enter the probabilities of two independent events to get every combination: both, either, exactly one, neither, and complements.",
    howTo: ["Enter probabilities as decimals between 0 and 1.", "Results use the multiplication, addition and complement rules."],
    examples: [{ problem: "P(A) = 0.5, P(B) = 0.3", answer: "P(A∪B) = 0.65" }],
    faqs: [{ q: "What does independent mean?", a: "Two events are independent if one happening does not change the probability of the other, so P(A and B) = P(A)·P(B)." }],
    related: ["combination-calculator", "statistics-calculator"],
    formulas: ["probability-rules", "binomial-probability"],
    keywords: ["probability calculator", "independent events calculator"],
  },
  {
    slug: "combination-calculator",
    title: "Combination & Permutation Calculator",
    shortTitle: "nCr / nPr",
    category: "statistics",
    icon: "Shuffle",
    description: "Compute combinations (nCr), permutations (nPr) and factorials with formulas and steps.",
    kind: "engine",
    fields: [
      { name: "type", label: "Type", type: "select", default: "c", options: [{ value: "c", label: "Combinations nCr (order doesn't matter)" }, { value: "p", label: "Permutations nPr (order matters)" }] },
      { name: "n", label: "n (total)", type: "number", default: "10" },
      { name: "r", label: "r (chosen)", type: "number", default: "3" },
    ],
    build: (v) => (v.type === "p" ? `P(${req(v.n, "n")},${req(v.r, "r")})` : `${req(v.n, "n")} choose ${req(v.r, "r")}`),
    intro: "Count selections and arrangements. Combinations ignore order; permutations count every ordering.",
    howTo: ["Choose combinations or permutations.", "Enter n and r (whole numbers, r ≤ n)."],
    examples: [{ problem: "10C3", answer: "120" }, { problem: "10P3", answer: "720" }],
    faqs: [{ q: "How do I know if order matters?", a: "If swapping two chosen items gives a different outcome (like a race podium), use permutations; if not (like a committee), use combinations." }],
    related: ["probability-calculator", "statistics-calculator"],
    formulas: ["combinations-formula"],
    keywords: ["combination calculator", "permutation calculator", "ncr calculator"],
  },
  {
    slug: "matrix-calculator",
    title: "Matrix Calculator",
    shortTitle: "Matrices",
    category: "linear-algebra",
    icon: "Grid3x3",
    description: "Matrix determinant, inverse, transpose, RREF, rank, eigenvalues, multiplication and addition with steps.",
    kind: "engine",
    fields: [
      { name: "op", label: "Operation", type: "select", default: "det", options: [{ value: "det", label: "Determinant" }, { value: "inverse", label: "Inverse" }, { value: "transpose", label: "Transpose" }, { value: "rref", label: "RREF (row reduce)" }, { value: "rank", label: "Rank" }, { value: "eigenvalues", label: "Eigenvalues" }, { value: "multiply", label: "A × B" }, { value: "add", label: "A + B" }, { value: "subtract", label: "A − B" }] },
      { name: "A", label: "Matrix A", type: "matrix", default: "[[2, 1, 3], [0, -1, 4], [1, 2, 0]]" },
      { name: "B", label: "Matrix B", type: "matrix", optional: true, default: "[[1, 0, 0], [0, 1, 0], [0, 0, 1]]", showIf: { field: "op", values: ["multiply", "add", "subtract"] } },
    ],
    build: (v) => {
      const A = req(v.A, "matrix A");
      const op = v.op ?? "det";
      if (["multiply", "add", "subtract"].includes(op)) return `${A} ${op === "multiply" ? "*" : op === "add" ? "+" : "-"} ${req(v.B, "matrix B")}`;
      return `${op} ${A}`;
    },
    intro: "Enter matrices in the grid editor (or as [[1,2],[3,4]]). Determinants show cofactor expansion, inverses show Gauss–Jordan elimination, and every result is verified (for example A·A⁻¹ = I).",
    howTo: ["Choose an operation.", "Set the size and fill in the entries.", "Review each row operation."],
    examples: [{ problem: "det [[1,2],[3,4]]", answer: "−2" }, { problem: "inverse [[2,1],[1,3]]", answer: "(1/5)[[3,−1],[−1,2]]" }],
    faqs: [{ q: "When is a matrix not invertible?", a: "When its determinant is 0 (the matrix is singular)." }],
    related: ["system-of-equations-calculator"],
    formulas: ["determinant-2x2", "matrix-inverse-2x2"],
    keywords: ["matrix calculator", "determinant calculator", "inverse matrix calculator"],
  },
  {
    slug: "unit-converter",
    title: "Unit Converter",
    shortTitle: "Units",
    category: "conversion",
    icon: "ArrowLeftRight",
    description: "Convert length, mass, volume, temperature, time and speed units with dimensional analysis steps.",
    kind: "engine",
    fields: [{ name: "value", label: "Value", type: "number", default: "5" }, { name: "from", label: "From unit", type: "text", default: "km" }, { name: "to", label: "To unit", type: "text", default: "miles" }],
    build: (v) => `convert ${req(v.value, "a value")} ${req(v.from, "a unit")} to ${req(v.to, "a unit")}`,
    intro: "Convert between metric and imperial units using conversion factors, and check that the units are compatible (dimensional analysis).",
    howTo: ["Enter a value and the units (e.g. km, mi, ft, kg, lb, °F, °C, L, gallon).", "The conversion factor and a round-trip check are shown."],
    examples: [{ problem: "5 km to miles", answer: "3.10686 mi" }, { problem: "100 °F to °C", answer: "37.78 °C" }],
    faqs: [{ q: "Why do temperatures convert differently?", a: "Celsius and Fahrenheit have different zero points, so the conversion adds an offset as well as scaling." }],
    related: ["scientific-calculator"],
    keywords: ["unit converter", "unit conversion calculator"],
  },
  {
    slug: "scientific-calculator",
    title: "Scientific Calculator",
    shortTitle: "Scientific",
    category: "arithmetic",
    icon: "Calculator",
    description: "Free online scientific calculator with trig, logs, powers, roots, factorials, memory and degree/radian modes.",
    kind: "scientific",
    intro: "A fast, keyboard-friendly scientific calculator. Supports trigonometric and inverse functions in degrees or radians, logarithms, powers, roots, factorials, constants and expression history.",
    howTo: ["Click buttons or type directly.", "Toggle DEG/RAD for trig functions.", "Press = or Enter to evaluate; use ANS to reuse the last answer."],
    examples: [{ problem: "sin(30°)", answer: "0.5" }, { problem: "5! / 3!", answer: "20" }],
    faqs: [{ q: "Does it follow the order of operations?", a: "Yes — expressions are parsed with standard precedence: parentheses, exponents, multiplication/division, addition/subtraction." }],
    related: ["graphing-calculator", "fraction-calculator", "percentage-calculator"],
    keywords: ["scientific calculator", "online calculator"],
  },
  {
    slug: "graphing-calculator",
    title: "Graphing Calculator",
    shortTitle: "Graphing",
    category: "graphing",
    icon: "LineChart",
    description: "Free online graphing calculator: plot multiple functions, zoom and pan, and find roots and intersections.",
    kind: "graph",
    intro: "Plot several functions at once on an interactive grid. Drag to pan, scroll or pinch to zoom, and the calculator marks roots, intersections and points you add.",
    howTo: ["Type a function such as x^2 - 4 or sin(x).", "Add more functions with “Add function”.", "Hover to read coordinates; roots and intersections are marked automatically."],
    examples: [{ problem: "y = x² − 4 and y = x + 2", answer: "Intersections at (−2, 0) and (3, 5)" }],
    faqs: [{ q: "Can I graph implicit equations like circles?", a: "Graph each half as a function, e.g. sqrt(25 - x^2) and -sqrt(25 - x^2)." }],
    related: ["quadratic-formula-calculator", "slope-calculator", "derivative-calculator"],
    keywords: ["graphing calculator", "function plotter", "graph functions online"],
  },
];

export const calculatorMap = new Map(CALCULATORS.map((c) => [c.slug, c]));

export function getCalculator(slug: string) {
  return calculatorMap.get(slug);
}
